# Configuration file for GeoPressureR parameters
#
# This file stores all the parameters used by the GeoPressureR functions, following the best
# practice to separate parameters from codes. This file is used with the config R package
# <https://rstudio.github.io/config/> which allows to retrieve the value of each parameter
# in your analysis files.
#
# This file is meant to be adapted based on your needs: feel free to add or remove parameters either
# in the default or for each tag. It is recommended to specify all parameters used, even if you
# use the default value.
#
# You can check the documentation of each function to learn what each of these parameters are doing
# as well as checking in 4-geopressure.R

default:
  #-- SET MAP ?tag_set_map()
  extent: !expr c(-100, -68, 0, 40) # c(W, E, S, N)
  scale: 5 # 1 (min) -> 1째 ; 2 -> 0.5째 ; 5 -> 0.25째 ; 10 (max) -> 0.1째
  include_min_duration: 0 # in hours
  #-- GEOPRESSURE ?geopressure_map()
  max_sample: 250
  margin: 20 # in hPa
  sd: 1
  thr_mask: 0.8
  # log_linear_pooling_weight:
  #-- GEOLIGHT ?twilight_create() ?geolight_map()
  # twl_thr:
  # twl_offset: 0 # in hours
  # twl_calib_adjust:
  # twl_llp:
  #-- GRAPH ?graph_create()
  thr_likelihood: 0.90
  thr_gs: 150 # km/h
  thr_as: 90 # km/h
  #-- MOVEMENT MODEL ?graph_set_movement()
  # movement_shape: 7
  # movement_scale: 7
  # movement_location: 40
  movement_low_speed_fix: 15 # km/h
  movement_type: "as"
  scientific_name: "Limnothlypis swainsonii"

CB594:
  #-- TAG ?tag_create()
  id: "CB594"
  crop_start: "2021-06-15"
  crop_end: "2022-05-21"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -80.44798,
                    known_lat = 32.76806)  # -1 -> last stap


CB596:
  #-- TAG ?tag_create()
  id: "CB596"
  crop_start: "2021-06-15"
  crop_end: "2022-05-21"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -80.35476,
                    known_lat = 33.219626)  # -1 -> last stap

CB598:
  #-- TAG ?tag_create()
  id: "CB598"
  crop_start: "2021-06-15"
  crop_end: "2022-06-09"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -84.1793,
                    known_lat = 35.28581)  # -1 -> last stap

CB599:
  #-- TAG ?tag_create()
  id: "CB599"
  crop_start: "2021-06-15"
  crop_end: "2022-05-16"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -84.0492,
                    known_lat = 35.43926)  # -1 -> last stap

CB601:
  #-- TAG ?tag_create()
  id: "CB601"
  crop_start: "2021-06-15"
  crop_end: "2022-06-04"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -84.0492,
                    known_lat = 35.43926)  # -1 -> last stap

CB608:
  #-- TAG ?tag_create()
  id: "CB608"
  crop_start: "2021-06-15"
  crop_end: "2022-05-03"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -91.19612,
                    known_lat = 36.66378)  # -1 -> last stap

CB611:
  #-- TAG ?tag_create()
  id: "CB611"
  crop_start: "2021-06-15"
  crop_end: "2022-05-03"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -91.19733,
                    known_lat = 36.65001)  # -1 -> last stap

CB616:
  #-- TAG ?tag_create()
  id: "CB616"
  crop_start: "2021-06-15"
  crop_end: "2022-06-14"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -82.301768,
                    known_lat = 37.294295)  # -1 -> last stap


CB619:
  #-- TAG ?tag_create()
  id: "CB619"
  crop_start: "2021-06-15"
  crop_end: "2022-06-10"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -82.304972,
                    known_lat = 37.286812)  # -1 -> last stap


CB620:
  #-- TAG ?tag_create()
  id: "CB620"
  crop_start: "2021-07-01"
  crop_end: "2022-06-10"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -82.305835,
                    known_lat = 37.293076)  # -1 -> last stap

CB621:
  #-- TAG ?tag_create()
  id: "CB621"
  crop_start: "2021-06-15"
  crop_end: "2022-05-01"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -90.95882,
                    known_lat = 30.65796)  # -1 -> last stap

CB623:
  #-- TAG ?tag_create()
  id: "CB623"
  crop_start: "2021-06-15"
  crop_end: "2022-04-15"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -90.99295,
                    known_lat = 30.47374)  # -1 -> last stap

CB624:
  #-- TAG ?tag_create()
  id: "CB624"
  crop_start: "2021-06-15"
  crop_end: "2022-04-26"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -91.36418,
                    known_lat = 30.41899)  # -1 -> last stap

CB627:
  #-- TAG ?tag_create()
  id: "CB627"
  crop_start: "2021-06-15"
  crop_end: "2022-05-03"
  known: !expr data.frame(stap_id = c(1, -1),
                    known_lon = -91.37109,
                    known_lat = 30.41565)  # -1 -> last stap
