# Configuration file for GeoPressureR parameters
#
# This file stores all the parameters used by the GeoPressureR functions, following the best
# practice to separate parameters from codes. These parameters are retrieved using config::get() of
# the config R package <https://rstudio.github.io/config/>.
#
# This file is meant to be adapted based on your needs: feel free to add parameters either in the
# default (applied to all tags) or for each tag seperatly (overwrite default). It is recommended to
# specify all parameters used, even if you use the default value.
#
# You can check the documentation of each function to learn what each of these parameters are doing
# as well as reading https://raphaelnussbaumer.com/GeoPressureManual/geopressuretemplate-workflow.html

default:
  tag_create: # ?tag_create()
    # crop_start: NULL # Generally set at the tag level
    # crop_end: NULL
  tag_set_map: # ?tag_set_map()
    extent: [-100, -68, 0, 40] # [W, E, S, N]
    scale: 5 # 1 (min) -> 1째 ; 2 -> 0.5째 ; 5 -> 0.25째 ; 10 (max) -> 0.1째
    include_stap_id: NULL # default, take all
    include_min_duration: 0 # in hours
  geopressure_map: # ?geopressure_map()
    max_sample: 250
    margin: 20 # in m
    sd: 0.6
    thr_mask: 0.9
    log_linear_pooling_weight: !expr \(n) 3*log(n)/n
  twilight_create: # ?twilight_create()
    # twl_thr: NULL
    # twl_offset: NULL # in hours
  geolight_map: # ?geolight_map()
    twl_calib_adjust: 1.4
    twl_llp: !expr \(n) log(n)/n
  graph_create: # ?graph_create()
    thr_likelihood: 0.99
    thr_gs: 150 # km/h
    # likelihood: NULL # Best to leave NULL.
  graph_add_wind:
    thr_as: 90 # km/h
  graph_set_movement: # ?graph_set_movement()
    type: "as"
    # method: "gamma"
    # shape: 7 # only for gamma
    # scale: 7
    # location: 40 # only for logistic
    # low_speed_fix: 15 # km/h
  graph_simulation: # ?graph_simulation()
    nj: 10
  pressurepath_create: # ?pressurepath_create()
    variable: ["altitude", "surface_pressure"]
    # solar_dep: 0
  geopressuretemplate: # ?geopressuretemplate()
    likelihood: ["map_pressure"] #  for nothing
    outputs: ["marginal", "most_likely", "simulation"]
    pressurepath: ["most_likely"] # "geopressureviz"
  bird_create:
    scientific_name: "Limnothlypis swainsonii"


CB594:
  tag_create:
    crop_start: "2021-06-15"
    crop_end: "2022-05-21"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -80.44798
      known_lat: 32.76806


CB596:
  tag_create:
    crop_start: "2021-06-15"
    crop_end: "2022-05-21"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -80.35476
      known_lat: 33.219626

CB598:
  tag_create:
    crop_start: "2021-06-15"
    crop_end: "2022-06-09"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -84.1793
      known_lat: 35.28581

CB599:
  #-- TAG ?tag_create()
  id: "CB599"
  crop_start: "2021-06-15"
  crop_end: "2022-05-16"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -84.0492
      known_lat: 35.43926

CB601:
  tag_create:
    crop_start: "2021-06-15"
    crop_end: "2022-06-04"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -84.0492
      known_lat: 35.43926

CB608:
  tag_create:
    crop_start: "2021-06-15"
    crop_end: "2022-05-03"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -91.19612
      known_lat: 36.66378

CB611:
  tag_create:
    crop_start: "2021-06-15"
    crop_end: "2022-05-03"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -91.19733
      known_lat: 36.65001

CB616:
  tag_create:
    crop_start: "2021-06-15"
    crop_end: "2022-06-14"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -82.301768
      known_lat: 37.294295


CB619:
  tag_create:
    crop_start: "2021-06-15"
    crop_end: "2022-06-10"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -82.304972
      known_lat: 37.286812


CB620:
  tag_create:
    crop_start: "2021-07-01"
    crop_end: "2022-06-10"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -82.305835
      known_lat: 37.293076

CB621:
  tag_create:
    crop_start: "2021-06-15"
    crop_end: "2022-05-01"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -90.95882
      known_lat: 30.65796

CB623:
  tag_create:
    crop_start: "2021-06-15"
    crop_end: "2022-04-15"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -90.99295
      known_lat: 30.47374

CB624:
  tag_create:
    crop_start: "2021-06-15"
    crop_end: "2022-04-26"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -91.36418
      known_lat: 30.41899

CB627:
  tag_create:
    crop_start: "2021-06-15"
    crop_end: "2022-05-03"
  tag_set_map:
    known:
      stap_id: [1, -1] # -1 -> last stap
      known_lon: -91.37109
      known_lat: 30.41565
